language: php
php:
  - 7.2
before_script:
  - composer self-update
  - composer install -n -o -d src
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - cd src
        - composer test