language: php
php:
  - 7.2
before_install:
  - chmod +x ./scripts/test.sh
install:
  - composer self-update
  - composer install -n -o -d src
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: ./scripts/test.sh